# Generated by Django 4.0.2 on 2022-02-04 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_Author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_relDate', models.DateTimeField(default=datetime.datetime(2022, 2, 4, 17, 25, 13, 910117))),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
