# Generated by Django 4.0.2 on 2022-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_delete_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_Author',
            new_name='book_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_relDate',
        ),
    ]
